### ISSUE TITLE
Cannot find module "modelo" 

### ISSUE THREAD

**Issue by opudalo** [kevinconway/Modelo.js#23]
Hello, 
some packages which depend on "modelo" broke.
Seems like with a recent release. 
An example would be firebase:
https://github.com/firebase/functions-samples/issues/249

Can you take a look. Thanks.

**Comment by andoma** [comment]
I've the same problem?

**Comment by kevinconway** [comment]
:man_facepalming: this is exactly why I dread making changes to stable libs. Looking into it. A quick fix should be to pin to `4.2.0` which does not include the NPM file changes that were just made.

**Comment by kevinconway** [comment]
I just pushed `4.2.2` which reverts all the recent changes. Let me know if this doesn't immediately resolve the issue.

**Comment by andoma** [comment]
I've still problems, but I'm no NPM expert, this is what I just tested with (pretty much clean slate)

````
$ cat package.json
{
  "name": "test",
  "version": "0.0.1",
  "dependencies": {
    "@google-cloud/pubsub": "^0.16.1"
  }
}

$ node
> require('@google-cloud/pubsub')
Error: Cannot find module 'modelo'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/andoma/src/xyz/node_modules/@google-cloud/common/src/operation.js:25:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)


$ npm info modelo

{ name: 'modelo',
  description: 'A JavaScript object inheritance utility.',
  'dist-tags': { latest: '4.2.2' },
  versions:
   [ '0.9.0',
     '1.0.0',
     '1.0.1',
     '1.0.2',
     '1.0.4',
     '2.0.0',
     '3.0.0',
     '3.1.0',
     '3.2.0',
     '4.0.0',
     '4.0.1',
     '4.0.2',
     '4.1.0',
     '4.1.1',
     '4.1.2',
     '4.2.0',
     '4.2.1',
     '4.2.2' ],
  maintainers: [ 'kevinconway <kevinjacobconway@gmail.com>' ],
  time:
   { modified: '2018-01-06T17:46:44.901Z',
     created: '2012-09-12T01:34:44.720Z',
     '0.9.0': '2012-09-12T01:34:46.333Z',
     '1.0.0': '2012-11-20T22:20:32.023Z',
     '1.0.1': '2013-03-16T23:32:26.734Z',
     '1.0.2': '2013-03-16T23:42:40.884Z',
     '1.0.4': '2013-10-26T00:54:18.406Z',
     '2.0.0': '2014-04-01T00:53:57.592Z',
     '3.0.0': '2014-04-05T04:52:56.571Z',
     '3.1.0': '2014-05-03T04:14:11.636Z',
     '3.2.0': '2014-05-03T05:15:15.039Z',
     '4.0.0': '2014-07-11T04:44:48.552Z',
     '4.0.1': '2014-07-18T01:53:31.867Z',
     '4.0.2': '2014-07-18T02:42:54.697Z',
     '4.1.0': '2014-08-26T04:57:05.001Z',
     '4.1.1': '2014-09-03T03:47:22.241Z',
     '4.1.2': '2014-09-07T00:59:58.652Z',
     '4.2.0': '2015-10-15T11:18:17.799Z',
     '4.2.1': '2018-01-06T16:31:50.842Z',
     '4.2.2': '2018-01-06T17:46:44.901Z' },
  author: 'Kevin Conway <kevinjacobconway@gmail.com> (https://github.com/kevinconway)',
  repository:
   { type: 'git',
     url: 'git://github.com/kevinconway/Modelo.js.git' },
  homepage: 'https://github.com/kevinconway/Modelo.js',
  bugs: { url: 'https://github.com/kevinconway/Modelo.js/issues' },
  readmeFilename: 'README.md',
  keywords:
   [ 'class',
     'classes',
     'inherit',
     'inherits',
     'inheritance',
     'mixin',
     'mix-in' ],
  users: { gregbabula: true },
  version: '4.2.2',
  main: './modelo/modelo.js',
  files: [ './modelo/modelo.js' ],
  scripts: { test: 'grunt' },
  dependencies: {},
  devDependencies:
   { augment: '^4.3.0',
     benchmark: '^1.0.0',
     'cli-table': '^0.3.0',
     'expect.js': '^0.3.1',
     fiber: '^1.0.4',
     grunt: '^0.4.4',
     'grunt-browserify': '^2.1.3',
     'grunt-contrib-uglify': '^0.4.0',
     'grunt-jslint': '^1.1.8',
     'grunt-mocha-test': '^0.10.2',
     'grunt-shell': '^0.7.0',
     klass: '^1.4.0',
     mocha: '^1.20.1' },
  optionalDependencies: {},
  engines: { node: '*' },
  gitHead: '417411293908bf6db6b93385e83c89d137d78ac5',
  dist:
   { integrity: 'sha512-/PUXUgjwDS+BE+aaiiz33uhZmoaWA7tqIoUI6z+1o6UaJ8PXmMDYwfxzwaX8uGsPzx1gXEusTPs/qFDqi/Gecw==',
     shasum: '8c9be3f0730b25e500bc67dd08094813b6dfa07a',
     tarball: 'https://registry.npmjs.org/modelo/-/modelo-4.2.2.tgz' },
  directories: {} }

````
This all worked fine yesterday though...

**Comment by sconix** [comment]
I can confirm 4.2.2 did not fix the issue, the package main is referencing to modelo/modelo.js file but no such file exists in the package.

**Comment by Seikilos** [comment]
When I execute `> npm install -g modelo`
 I get the following package contents:
![grafik](https://user-images.githubusercontent.com/1260908/34642526-a802a4d8-f314-11e7-8419-95a94b69af81.png)

There are no files. I think this is the issue.

**Comment by stephenplusplus** [comment]
@kevinconway I'm not sure what happened, it seems like package.json is configured properly with `main` and `files`, but just some things you could try:

- Update to the latest npm (`npm install -g npm`) before publishing
- Make sure the `./modelo/modelo.js` file exists locally
- Try `npm pack` to see exactly the contents of the tarball that will be published, before publishing

**Comment by kevinconway** [comment]
OK. I'm thinking there was a change in NPM over the past few years that I didn't account for. It appears the way it interprets the paths placed in the `files` directive no longer works the way it used to. I've pushed up a new version that contains the code files and opened a PR to fix the issue permanently. https://github.com/kevinconway/Modelo.js/pull/24

**Comment by Seikilos** [comment]
@kevinconway Fixed firebase issue for me. Thanks!

**Comment by Seikilos** [comment]
Update to 4.2.3 which did the trick. The package was broken. firebase is now working when I install the latest modelo library.

**Comment by andoma** [comment]
Yes, works for me as well now. Thanks for quick fix

**Comment by kevinconway** [comment]
I'm sorry to have disrupted everyone's day. I should have been _much_ more cautious when updating something after multiple years of sitting stable. I let myself get lulled into the "but it's just a metadata change" thinking and did not practice due diligence in vetting the release before I published it. I hope everyone's day and builds work out better now.

I appreciate everyone jumping in to help out and share debug data. I'm going to close the issue as resolved. Please re-open it or create a new issue if there are any more problems. I'll keep this in a bookmark somewhere as a cautionary tale so when, in another 3 - 5 years, I consider another NPM file update I don't make the same mistake.
